// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};

export type Data = {
    uuid: string;
    title: string;
    pwHash: unknown;
    encrypted: string;
    expires: string;
    iv: string;
};

export type OcsMeta = {
    status: string;
    statuscode: number;
    message?: string;
    totalitems?: string;
    itemsperpage?: string;
};

export type PageIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/index.php/apps/secrets';
};

export type PageIndexResponses = {
    /**
     * Return secrets page
     */
    200: string;
};

export type PageIndexResponse = PageIndexResponses[keyof PageIndexResponses];

export type PageShowData = {
    body?: never;
    path: {
        /**
         * The uuid of the secret
         */
        uuid: string;
    };
    query?: never;
    url: '/index.php/apps/secrets/s/{uuid}';
};

export type PageShowResponses = {
    /**
     * Return secrets page and show specific secret
     */
    200: string;
};

export type PageShowResponse = PageShowResponses[keyof PageShowResponses];

export type SecretShareShowShareData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/index.php/apps/secrets/share/{token}';
};

export type SecretShareShowShareResponses = {
    /**
     * Show secret share page
     */
    200: string;
};

export type SecretShareShowShareResponse = SecretShareShowShareResponses[keyof SecretShareShowShareResponses];

export type SecretShareShowAuthenticateData = {
    body?: never;
    path: {
        token: string;
        redirect: string;
    };
    query?: never;
    url: '/index.php/apps/secrets/share/{token}/authenticate/{redirect}';
};

export type SecretShareShowAuthenticateResponses = {
    /**
     * Show authentication page
     */
    200: string;
};

export type SecretShareShowAuthenticateResponse = SecretShareShowAuthenticateResponses[keyof SecretShareShowAuthenticateResponses];

export type RedirectShareData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/index.php/apps/secrets/show/{token}';
};

export type RedirectShareResponses = {
    /**
     * Show secret share page
     */
    200: string;
};

export type RedirectShareResponse = RedirectShareResponses[keyof RedirectShareResponses];

export type SecretApiGetAllData = {
    body?: never;
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path?: never;
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets';
};

export type SecretApiGetAllResponses = {
    /**
     * Return list of secrets
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: Array<{
                uuid: string;
                title: string;
                pwHash: unknown;
                encrypted: string;
                expires: string;
                iv: string;
            }>;
        };
    };
};

export type SecretApiGetAllResponse = SecretApiGetAllResponses[keyof SecretApiGetAllResponses];

export type SecretApiCreateSecretData = {
    body: {
        /**
         * The title of the secret (visible to the owner only)
         */
        title: string;
        /**
         * The encrypted secret to store
         */
        encrypted: string;
        /**
         * The iv for the encrypted secret
         */
        iv: string;
        /**
         * (Optional) expiration date for the secret
         */
        expires?: string | null;
        /**
         * (Optional) password to protect the secret share
         */
        password?: string | null;
    };
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path?: never;
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets';
};

export type SecretApiCreateSecretErrors = {
    /**
     * Unauthorized
     */
    401: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiCreateSecretError = SecretApiCreateSecretErrors[keyof SecretApiCreateSecretErrors];

export type SecretApiCreateSecretResponses = {
    /**
     * Secret created
     */
    201: {
        ocs: {
            meta: OcsMeta;
            data: Data;
        };
    };
};

export type SecretApiCreateSecretResponse = SecretApiCreateSecretResponses[keyof SecretApiCreateSecretResponses];

export type SecretApiDeleteData = {
    body?: never;
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path: {
        /**
         * The uuid of the secret
         */
        uuid: string;
    };
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}';
};

export type SecretApiDeleteErrors = {
    /**
     * Secret not found
     */
    404: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiDeleteError = SecretApiDeleteErrors[keyof SecretApiDeleteErrors];

export type SecretApiDeleteResponses = {
    /**
     * Secret deleted
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiDeleteResponse = SecretApiDeleteResponses[keyof SecretApiDeleteResponses];

export type SecretApiGetData = {
    body?: never;
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path: {
        /**
         * The uuid of the secret
         */
        uuid: string;
    };
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}';
};

export type SecretApiGetErrors = {
    /**
     * Secret not found
     */
    404: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiGetError = SecretApiGetErrors[keyof SecretApiGetErrors];

export type SecretApiGetResponses = {
    /**
     * Return secret with given uuid
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: Data;
        };
    };
};

export type SecretApiGetResponse = SecretApiGetResponses[keyof SecretApiGetResponses];

export type SecretApiUpdateTitleData = {
    body: {
        /**
         * The new title of the secret
         */
        title: string;
    };
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path: {
        /**
         * The uuid of the secret
         */
        uuid: string;
    };
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}/title';
};

export type SecretApiUpdateTitleErrors = {
    /**
     * Secret not found
     */
    404: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiUpdateTitleError = SecretApiUpdateTitleErrors[keyof SecretApiUpdateTitleErrors];

export type SecretApiUpdateTitleResponses = {
    /**
     * Return updated secret
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: Data;
        };
    };
};

export type SecretApiUpdateTitleResponse = SecretApiUpdateTitleResponses[keyof SecretApiUpdateTitleResponses];

export type SecretApiRetrieveSharedSecretData = {
    body: {
        /**
         * The uuid of the secret
         */
        uuid: string;
        /**
         * The password for the secret share
         */
        password?: string | null;
    };
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path?: never;
    query?: never;
    url: '/ocs/v2.php/apps/secrets/api/v1/share';
};

export type SecretApiRetrieveSharedSecretErrors = {
    /**
     * Unauthorized
     */
    401: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
    /**
     * Secret not found for uuid
     */
    404: {
        ocs: {
            meta: OcsMeta;
            data: {
                message: string;
            };
        };
    };
};

export type SecretApiRetrieveSharedSecretError = SecretApiRetrieveSharedSecretErrors[keyof SecretApiRetrieveSharedSecretErrors];

export type SecretApiRetrieveSharedSecretResponses = {
    /**
     * Return requested secret
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: {
                iv: string;
                encrypted: string;
            };
        };
    };
};

export type SecretApiRetrieveSharedSecretResponse = SecretApiRetrieveSharedSecretResponses[keyof SecretApiRetrieveSharedSecretResponses];

export type SecretApiGetVersionData = {
    body?: never;
    headers: {
        /**
         * Required to be true for the API request to pass
         */
        'OCS-APIRequest': boolean;
    };
    path?: never;
    query?: never;
    url: '/ocs/v2.php/apps/secrets/version';
};

export type SecretApiGetVersionResponses = {
    /**
     * Return application/api version
     */
    200: {
        ocs: {
            meta: OcsMeta;
            data: {
                version: string;
            };
        };
    };
};

export type SecretApiGetVersionResponse = SecretApiGetVersionResponses[keyof SecretApiGetVersionResponses];
