// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PageIndexData, PageIndexResponses, PageShowData, PageShowResponses, RedirectShareData, RedirectShareResponses, SecretApiCreateSecretData, SecretApiCreateSecretErrors, SecretApiCreateSecretResponses, SecretApiDeleteData, SecretApiDeleteErrors, SecretApiDeleteResponses, SecretApiGetAllData, SecretApiGetAllResponses, SecretApiGetData, SecretApiGetErrors, SecretApiGetResponses, SecretApiGetVersionData, SecretApiGetVersionResponses, SecretApiRetrieveSharedSecretData, SecretApiRetrieveSharedSecretErrors, SecretApiRetrieveSharedSecretResponses, SecretApiUpdateTitleData, SecretApiUpdateTitleErrors, SecretApiUpdateTitleResponses, SecretShareShowAuthenticateData, SecretShareShowAuthenticateResponses, SecretShareShowShareData, SecretShareShowShareResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Return secrets page
 */
export const pageIndex = <ThrowOnError extends boolean = false>(options?: Options<PageIndexData, ThrowOnError>) => (options?.client ?? client).get<PageIndexResponses, unknown, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/index.php/apps/secrets',
    ...options
});

/**
 * Return secrets page and show specific secret
 */
export const pageShow = <ThrowOnError extends boolean = false>(options: Options<PageShowData, ThrowOnError>) => (options.client ?? client).get<PageShowResponses, unknown, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/index.php/apps/secrets/s/{uuid}',
    ...options
});

/**
 * Show shared secret page
 */
export const secretShareShowShare = <ThrowOnError extends boolean = false>(options: Options<SecretShareShowShareData, ThrowOnError>) => (options.client ?? client).get<SecretShareShowShareResponses, unknown, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/index.php/apps/secrets/share/{token}',
    ...options
});

/**
 * Show the authentication page The form has to submit to the authenticate method route
 */
export const secretShareShowAuthenticate = <ThrowOnError extends boolean = false>(options: Options<SecretShareShowAuthenticateData, ThrowOnError>) => (options.client ?? client).get<SecretShareShowAuthenticateResponses, unknown, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/index.php/apps/secrets/share/{token}/authenticate/{redirect}',
    ...options
});

/**
 * Show shared secret page
 */
export const redirectShare = <ThrowOnError extends boolean = false>(options: Options<RedirectShareData, ThrowOnError>) => (options.client ?? client).get<RedirectShareResponses, unknown, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/index.php/apps/secrets/show/{token}',
    ...options
});

/**
 * Get all secrets for authenticated user
 */
export const secretApiGetAll = <ThrowOnError extends boolean = false>(options: Options<SecretApiGetAllData, ThrowOnError>) => (options.client ?? client).get<SecretApiGetAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets',
    ...options
});

/**
 * Store an e2e encrypted secret and return a share URL (without key portion)
 */
export const secretApiCreateSecret = <ThrowOnError extends boolean = false>(options: Options<SecretApiCreateSecretData, ThrowOnError>) => (options.client ?? client).post<SecretApiCreateSecretResponses, SecretApiCreateSecretErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete the secret with the given uuid
 */
export const secretApiDelete = <ThrowOnError extends boolean = false>(options: Options<SecretApiDeleteData, ThrowOnError>) => (options.client ?? client).delete<SecretApiDeleteResponses, SecretApiDeleteErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}',
    ...options
});

/**
 * Get secret with given uuid
 */
export const secretApiGet = <ThrowOnError extends boolean = false>(options: Options<SecretApiGetData, ThrowOnError>) => (options.client ?? client).get<SecretApiGetResponses, SecretApiGetErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}',
    ...options
});

/**
 * Update the title of a secret
 */
export const secretApiUpdateTitle = <ThrowOnError extends boolean = false>(options: Options<SecretApiUpdateTitleData, ThrowOnError>) => (options.client ?? client).put<SecretApiUpdateTitleResponses, SecretApiUpdateTitleErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/secrets/{uuid}/title',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return the shared secret for the given uuid
 */
export const secretApiRetrieveSharedSecret = <ThrowOnError extends boolean = false>(options: Options<SecretApiRetrieveSharedSecretData, ThrowOnError>) => (options.client ?? client).post<SecretApiRetrieveSharedSecretResponses, SecretApiRetrieveSharedSecretErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/api/v1/share',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return the secrets app/api version
 */
export const secretApiGetVersion = <ThrowOnError extends boolean = false>(options: Options<SecretApiGetVersionData, ThrowOnError>) => (options.client ?? client).get<SecretApiGetVersionResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'basic', type: 'http' }],
    url: '/ocs/v2.php/apps/secrets/version',
    ...options
});
