# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint (eslint)

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'appinfo/info.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  workflow_call:

permissions:
  contents: read

concurrency:
  group: lint-eslint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    name: eslint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Lint
        run: pnpm run lint
