# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: openapi-checks
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Generate openapi spec
        run: make openapi
      - name: Validate no changes
        run: |
          git checkout HEAD composer.json composer.lock vendor-bin
          git status --porcelain
          [[ "$(git status --porcelain | wc -l)" -eq 0 ]] || {
            echo "git repository is dirty -> openapi has changed"
            exit 1
          }
