# SPDX-FileCopyrightText: Tobias Knöppler <tobias@knoeppler.org>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - "v*"
      - "test*"

jobs:
  e2e-test:
    uses: ./.github/workflows/e2e-tests.yml
  lint-eslint:
    uses: ./.github/workflows/lint-eslint.yml
  lint-info-xml:
    uses: ./.github/workflows/lint-info-xml.yml
  lint-php:
    uses: ./.github/workflows/lint-php.yml
  lint-php-cs:
    uses: ./.github/workflows/lint-php-cs.yml
  phpunit-mysql:
    uses: ./.github/workflows/phpunit-mysql.yml
  phpunit-pgsql:
    uses: ./.github/workflows/phpunit-pgsql.yml
  phpunit-sqlite:
    uses: ./.github/workflows/phpunit-sqlite.yml
  reuse:
    uses: ./.github/workflows/reuse.yml
  release:
    needs:
      - e2e-test
      - lint-eslint
      - lint-info-xml
      - lint-php
      - lint-php-cs
      - phpunit-mysql
      - phpunit-pgsql
      - phpunit-sqlite
      - reuse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: secrets
    - name: Verify correct versions
      if: ${{ !startsWith( github.ref, 'refs/tags/test') }}
      working-directory: ./secrets
      run: |
        set -eu
        VERSION="${GITHUB_REF##*/}"
        VERSION="${VERSION#v}"
        grep "<version>${VERSION?}</version>" appinfo/info.xml || {
          echo "appinfo/info.xml: version does not match git tag ($VERSION)"
          exit 1
        }
        [[ "$(jq -r '.version' < package.json)" == "$VERSION" ]] || {
          echo "package.json: version does not match git tag ($VERSION)"
          exit 1
        }
        [[ "$(jq -r '.version' < cli/package.json)" == "$VERSION" ]] || {
          echo "cli/package.json: version does not match git tag ($VERSION)"
          exit 1
        }
        
        echo "Version check successful"
    - name: Set up php 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        tools: phpunit
        extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql
        coverage: none

    - name: Read package.json node and npm engines version
      uses: skjnldsv/read-package-engines-version-actions@v1.2
      id: versions
      with:
        fallbackNode: '^12'
        fallbackNpm: '^6'
        path: './secrets'

    - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodeVersion }}
    - uses: oven-sh/setup-bun@v1
    - name: Build app
      working-directory: ./secrets
      run: |
        npm install --dev
        make build appstore
    - name: Build cli
      working-directory: ./secrets/cli
      run: |
        bun install --dev
        bun build --compile ./cli.ts --outfile nc-secrets
        tar -caf nc-secrets-cli.tar.gz nc-secrets
        mv nc-secrets-cli.tar.gz ../build/artifacts/
    - name: "Create release"
      working-directory: ./secrets/build/artifacts/appstore
      run: |
        set -x
        sha256sum secrets.tar.gz > secrets.sha256
        tag_name="${GITHUB_REF##*/}"
        description="$(git tag -n10 --format="%(contents)" test-release-with-cli-1)"
        gh release create --draft -t "${tag_name?}" -F - "${tag_name?}" <<EOF
        ${description}
        EOF
        mv ../nc-secrets-cli.tar.gz ./
        for asset in secrets.tar.gz secrets.sha256 nc-secrets-cli.tar.gz
        do
          gh release upload "${tag_name?}" "${asset?}"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

