# SPDX-FileCopyrightText: Tobias Knöppler <thecalcaholic@web.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - "v*"
      - "test*"

jobs:
  integration-test:
    uses: ./.github/workflows/integration-tests.yml
  release:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: secrets

    - name: Set up php 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: phpunit
        extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql
        coverage: none

    - name: Read package.json node and npm engines version
      uses: skjnldsv/read-package-engines-version-actions@v1.2
      id: versions
      with:
        fallbackNode: '^12'
        fallbackNpm: '^6'
        path: './secrets'

    - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodeVersion }}
    - uses: oven-sh/setup-bun@v1
    - name: Build app
      working-directory: ./secrets
      run: |
        npm install --dev
        make build
    - name: Build cli
      working-directory: ./secrets/cli
      run: |
        cp ../src/crypto.js ./crypto.import.js
        bun install --dev
        bun build --compile ./cli.ts --outfile nc-secrets
        tar -caf nc-secrets-cli.tar.gz nc-secrets
    - name: "Create release"
      run: |
        set -x
        make build
        mkdir secrets
        mv appinfo img js lib l10n LICENSES templates LICENSE.md secrets/
        tar -caf secrets.tar.gz secrets
        sha256sum secrets.tar.gz > secrets.sha256
        tag_name="${GITHUB_REF##*/}"
        description="$(git tag -n10 --format="%(contents)" test-release-with-cli-1)"
        gh release create --draft -t "${tag_name?}" -F - "${tag_name?}" <<EOF
        ${description}
        EOF
        mv cli/nc-secrets-cli.tar.gz ./
        for asset in secrets.tar.gz secrets.sha256 nc-secrets-cli.tar.gz
        do
          gh release upload "${tag_name?}" "${asset?}"
        done

      working-directory: ./secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

